import type { Metadata } from "next";

export const metadata: Metadata = { title: "Website Privacy Policy — Demand Group", description: "How Demand Group processes information when you visit its website." };

export default function WebsitePrivacyPolicy() {
  return <main className="policy-page"><nav className="policy-nav"><a className="wordmark" href="/"><span className="mark">DG</span><span>Demand Group</span></a><a href="/">Back to studio</a></nav><article className="policy-document">
    <header><p>Demand Group website</p><h1>Website Privacy Policy</h1><p className="policy-date"><strong>Last updated:</strong> 14 August 2026</p></header>
    <p>This notice describes the processing of personal data connected with the Demand Group presentation website, in accordance with Regulation (EU) 2016/679 (GDPR) and applicable Italian privacy law.</p>
    <h2>Data controller</h2><p>The controller is <strong>Demand Group</strong>, an independent studio based in Italy. Privacy enquiries may be sent to <a href="mailto:demandgroup@tuta.io">demandgroup@tuta.io</a>.</p>
    <h2>Data processed</h2><p>The website does not provide user accounts, contact forms, advertising, behavioural profiling or audience analytics. When a visitor accesses the website, hosting and network providers may automatically process technical connection data such as IP address, requested resource, date and time, browser information and security logs. Demand Group does not use this information to identify or profile visitors.</p><p>If you contact us by email, we process your address, message and any information you choose to provide only to answer and manage the correspondence.</p>
    <h2>Purposes and legal bases</h2><ul><li>Delivering, securing and maintaining the website: legitimate interests and, where applicable, steps requested by the visitor.</li><li>Answering emails and business enquiries: steps requested by the sender and legitimate interests in managing communications.</li><li>Complying with legal obligations or defending legal claims where necessary.</li></ul>
    <h2>Recipients and international transfers</h2><p>The website is published through GitHub Pages. Technical data may therefore be processed by GitHub and its service providers under their own privacy terms and appropriate transfer mechanisms. Data may also be disclosed when required by law. Demand Group does not sell personal data.</p>
    <h2>Retention</h2><p>Demand Group does not maintain a visitor database. Technical logs are retained by hosting providers according to their operational and security policies. Email correspondence is kept only as long as reasonably necessary for the request, business relationship, legal obligations or defence of claims.</p>
    <h2>Your rights</h2><p>Subject to the conditions of the GDPR, you may request access, rectification, erasure, restriction, portability or objection, and may withdraw consent at any time without affecting earlier processing. Contact <a href="mailto:demandgroup@tuta.io">demandgroup@tuta.io</a>. You may also lodge a complaint with the Italian Data Protection Authority (Garante per la protezione dei dati personali).</p>
    <h2>Cookies</h2><p>See the <a href="/cookie-policy/">Cookie Policy</a> for details and use <button className="footer-link" type="button" data-cookie-settings>Cookie settings</button> to review your choice.</p>
    <h2>Italian summary</h2><p>Questo sito non utilizza account, moduli di contatto, pubblicità, profilazione o strumenti analytics. I fornitori tecnici possono trattare dati di connessione necessari a erogare e proteggere il sito. Per esercitare i diritti previsti dal GDPR o chiedere chiarimenti: <a href="mailto:demandgroup@tuta.io">demandgroup@tuta.io</a>.</p>
  </article><footer className="policy-footer"><span>© 2026 Demand Group</span><div><a href="/cookie-policy/">Cookie Policy</a><a href="/privacy-policy/">App Privacy Policy</a></div></footer></main>;
}
